# Generated by Django 3.2.9 on 2023-04-23 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.TextField()),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.annee_academique')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.niveau')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.session')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.type_document')),
            ],
        ),
    ]
