# Generated by Django 3.1.2 on 2023-07-05 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_auto_20230705_1300'),
        ('document', '0002_auto_20230705_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='examen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametres.examen'),
            preserve_default=False,
        ),
    ]
