# Generated by Django 3.1.2 on 2023-07-19 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_auto_20230705_1300'),
        ('document', '0003_document_examen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='session',
        ),
        migrations.AddField(
            model_name='document',
            name='session1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='session1', to='parametres.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='session2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='session2', to='parametres.session'),
            preserve_default=False,
        ),
    ]
