# Generated by Django 3.1.2 on 2023-07-06 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametres', '0002_auto_20230705_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.TextField()),
                ('nom_complet', models.TextField()),
                ('fichier', models.TextField()),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.annee_academique')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.examen')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.niveau')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.session')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.type_document')),
            ],
        ),
    ]
